### ISSUE TITLE
[esp32] The data sent in the first is correct and everything else is incorrect

### ISSUE THREAD

**Issue by dtboy1995** [4-20ma/ModbusMaster#105]
this my code fragment
```c++
delay(10000);
node.writeMultipleRegisters(0x101, 0x01);
```
this is serial output 
```log
01 10 01 01 00 01 02 00 00 B7 41 ☑ 
E4 C6 CB 79 1B 62 52 92 D6 A6 A5   ✘
B6 E9 EB B0 87 66 EF F4 D1 DD 23  ✘
A7 03 E6 1B 59 73 78 03 FD 34 A8   ✘
```
can someone help explain why this is happening?
thank you very much.

**Comment by marcolettieri** [comment]
have you solved this issue? we're experiencing the same here

**Comment by dtboy1995** [comment]
@lettierimarco , hello 
you can use hardwareSerail(1) instead of  hardwareSerail(2) to solve this problem
