### ISSUE TITLE
Read Holding Register

### ISSUE THREAD

**Issue by MohdShanawaz** [4-20ma/ModbusMaster#122]
I am trying to read holding register of Elmeasure Energy Meter (5310). 
Standard : Modbus RTU protocol (Half duplex)

`#include <ModbusMaster.h>

/*!
  We're using a MAX485-compatible RS485 Transceiver.
  Rx/Tx is hooked up to the hardware serial port at 'Serial'.
  The Data Enable and Receiver Enable pins are hooked up as follows:
*/
#define MAX485_DE      3
#define MAX485_RE_NEG  2

// instantiate ModbusMaster object
ModbusMaster node;

void preTransmission()
{
  digitalWrite(MAX485_RE_NEG, 1);
  digitalWrite(MAX485_DE, 1);
}

void postTransmission()
{
  digitalWrite(MAX485_RE_NEG, 0);
  digitalWrite(MAX485_DE, 0);
}

void setup()
{
  pinMode(MAX485_RE_NEG, OUTPUT);
  pinMode(MAX485_DE, OUTPUT);
  // Init in receive mode
  digitalWrite(MAX485_RE_NEG, 0);
  digitalWrite(MAX485_DE, 0);

  // Modbus communication runs at 9600 baud
  Serial.begin(9600);

  // Modbus slave ID 8
  node.begin(1, Serial);
  // Callbacks allow us to configure the RS485 transceiver correctly
  node.preTransmission(preTransmission);
  node.postTransmission(postTransmission);
}

void loop()
{
  uint8_t resultMain;
  float value;
      

  resultMain = node.readHoldingRegisters(1,10);
  if (resultMain == node.ku8MBSuccess)
  {
      Serial.println("Success");
      Serial.print("Value: ");
      value = node.getResponseBuffer(1);
      Serial.println(value);
  }
  else
  {
  Serial.println("Error");
  }
}`

![Register Map](https://user-images.githubusercontent.com/35393053/57174700-7af05f80-6e60-11e9-9201-f4ca76772836.png)

![image](https://user-images.githubusercontent.com/35393053/57174906-34503480-6e63-11e9-9ac5-037c30521b81.png)

**Comment by DineshMudumala** [comment]
@MohdShanawaz i was using similar slave devices which store the float having same error. just to know did you get any changes such your code is working
