### ISSUE TITLE
Request timeout is impatient

### ISSUE THREAD

**Issue by madpenguin8** [4-20ma/ModbusMaster#3]
I found that having a uint8_t is not enough of delay when trying to connect to an air compressor using your library. It seems that due to the nature of the design requests for certain registers requires long delays and a uint8_t is not enough. I bumped up ku8MBResponseTimeout to a uint16_t at 2000 millisecond delay time and everything began to work perfectly. 

I have a potential fix that uses a uint16_t instead and it includes an overload constructor
ModbusMaster(uint8_t u8SerialPort, uint8_t u8MBSlave, uint16_t u16ResponseTimeout)

This should give the library greater flexibility of having a longer timeout that is easier to configure. I will test it out in the next few days and let you know. In the meantime, are there any reasons why uint8 was chosen, I'm not a Modbus expert so I'm not sure if there is a standard.

**Comment by 4-20ma** [comment]
Fixed via PR #10.

**Comment by madpenguin8** [comment]
For some reason I didn't see a notification on this until today, thanks for the enhancement!

**Comment by Askari110** [comment]
Hi madpenguin8,

How could you done this, kindly do assist me in this.
