### ISSUE TITLE
Code not work with arduino mega 2560 115200 baud rate

### ISSUE THREAD

**Issue by tuhuynh** [4-20ma/ModbusMaster#32]
I used this code to read holding register with baud rate  setup is 115200. it didn't work. If i set 57600 baud rate it work very good. I don't know this error from my Mega 2560 or modbus master code??? 
I wrote a test code to print "Hello world" with 115200 baud rate, It worked good????? please help me to  check this problem??thanks.

**Comment by tuhuynh** [comment]
If after "node.begin(115200)" i use "Serial.begin(115200)", code modbus work good. I think this modbus lib have a broblem but don't find out what happend make this error with mega 2560.

**Comment by tuhuynh** [comment]
Function readHoldingRegister() use to read up to 125 16bit registers, but responebuffer array have only 64 16bit element so it can't fit for readHoldingRegister() function when read 125 register at once. We must increase ku8MaxBufferSize to 125 to fix this problem.

**Comment by 4-20ma** [comment]
Can you confirm that this works after changing `ku8MaxBufferSize` to 125?

**Comment by 4-20ma** [comment]
Closed due to inactivity.
