### ISSUE TITLE
Default enabling of __MODBUSMASTER_DEBUG__ leads to unpredictable behavior in sketches, suggest setting to 0 by default

### ISSUE THREAD

**Issue by LukeRiceApperson** [4-20ma/ModbusMaster#35]
First off, great library and thanks for making it, overall I've been very happy with it and it has worked perfectly for my project. 

However, these few lines were causing some odd behavior in my system that it took me a while to track down. 

````ModbusMaster.cpp lines 150-153:````
````
#if __MODBUSMASTER_DEBUG__
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
#endif
````

The way I constructed my application is part of the reason it took a while, but generally I don't expect a library to change the state of pins in a hidden way. I recommend setting __MODBUSMASTER_DEBUG__ to 0 by default, since if you intend to use the debugging features you will have no issue in enabling them, but most users will probably not be aware of this functionality and are more likely to be using digital pins 4 and 5. 

If nothing else, it would be good to make the fact that this is enabled by default very obvious and mention it in the main README. 

Thanks again for the library.

**Comment by kintel** [comment]
+1

Does it help if this is made a pull request so it can be accepted with one click?
