### ISSUE TITLE
arduino 1.0.6 Help

### ISSUE THREAD

**Issue by ingeltro** [4-20ma/ModbusMaster#36]
hello I have a program that only runs on IDE 1.0.6 and wish to add the Modbus instruction but the latter does not work with IDE 1.0.6, which I do? ..

**Comment by 4-20ma** [comment]
I've successfully used this library with Arduino IDE as far back as 16 (prior to the 1.x release series). It is currently compatible with the 1.6 series releases. Can you elaborate on the specific issue (e.g. what is the error message? what version of the ModbusMaster library are you using)?

**Comment by 4-20ma** [comment]
Closed due to inactivity.
