### ISSUE TITLE
Arduino DUE and Serial1,2,3

### ISSUE THREAD

**Issue by silas15** [4-20ma/ModbusMaster#38]
Hi, thanks for super library.

I have problem with using different serial other then serial 0. On UNO si code fast and without problems. On DUE works slowly (but works). Serial1(2,3) on DUE didn't work at all. It sends nothing. I tried:
`ModbusMaster node(Serial1,1);`
`ModbusMaster node(1,1); `
Comunication not working.

I using library version 0.11.0, arduino IDE 1.6.8

Only corrections I made, is adding lines for TX enable and
`MBSerial->begin(u16BaudRate, SERIAL_8E1)` 

Code works on UNO without any problems.

**Comment by theurlm** [comment]
Hy, can you show me the code of the modifications of TX enable and SERIAL_8E1 ?

**Comment by silas15** [comment]
I found the problem. Below line:
`MBSerial->begin(u16BaudRate);`
i add
`Serial1.begin(9600, SERIAL_8E1);`
Then serial prot works with parity.
I don't understand how it works, but i'm happy.

For TX enable I just add digital write high function above line:
`MBSerial->flush();`

**Comment by 4-20ma** [comment]
Glad it's working. Thanks. Closing issue.
