### ISSUE TITLE
Arduino Leonardo and ModbusMaster

### ISSUE THREAD

**Issue by hanusek** [4-20ma/ModbusMaster#4]
Hello, I have a problem.
When I wanted to compile the example program the compiler returns an error:

ModbusMaster.cpp:36: error: conversion from ‘Serial_’ to non-scalar type ‘HardwareSerial’ requested
arduino-1.0.5/libraries/ModbusMaster/ModbusMaster.cpp: In member function ‘void ModbusMaster::begin(uint16_t)’:
arduino-1.0.5/libraries/ModbusMaster/ModbusMaster.cpp:139: error: no match for ‘operator=’ in ‘MBSerial = Serial’
arduino-1.0.5/hardware/arduino/cores/arduino/HardwareSerial.h:33: note: candidates are: HardwareSerial& HardwareSerial::operator=(const HardwareSerial&)

How to solve it?

**Comment by 4-20ma** [comment]
This should be fixed by PR #2. Please open another issue if it does not work for you.
