### ISSUE TITLE
ReadHoldindRegister

### ISSUE THREAD

**Issue by pedrofelipest** [4-20ma/ModbusMaster#41]
So I hope that somebody has gone though the same issue as me; 
I'm trying to obtain the content of a holding register through the serial port. I can see the content but it's not understandable. What I'm getting It's not ASCII or any other variable type.
`resut = node.readHoldingRegisters(25, 6);`

**Comment by samdee21** [comment]
Can you please give us an example of content the data that is coming through - have you tried swapping A&B wires round?

**Comment by 4-20ma** [comment]
Per @samdee21, can you please elaborate on what you're seeing? Note: close issue on 23 Sep 2016 if no response.

**Comment by 4-20ma** [comment]
Closed due to inactivity.
