### ISSUE TITLE
Change license to Apache 2.0

### ISSUE THREAD

**Issue by 4-20ma** [4-20ma/ModbusMaster#45]
Make the following changes after source code changes have been merged.

- [x] Remove `COPYING` (GPLv3)
- [x] Add `LICENSE` (Apache-2.0)
- [ ] Update README badge
- [x] Update README license text
- [ ] Update license text in each source file

**Comment by kintel** [comment]
For the record, feel free to relicense any contributions I've made under any Open Source license.

**Comment by 4-20ma** [comment]
When I originally wrote ModbusMaster, it was partly to solve a problem (extract real-time data from a PLC), and partly as an exercise in learning. I was inspired by and borrowed concepts from [Arduino Modbus Master](http://sites.google.com/site/jpmzometa/arduino-mbrt/arduino-modbus-master). I believe in Open Source Software and the concept that sharing/applying ideas from multiple contributors make a better overall product.

This library is successful when people use it to solve real-world problems and contribute their improvements to the project. It may be used in open source, public domain, private, or commercial projects. When someone links to this library, it becomes a derivative work of this code. The GPLv3 requires distribution of this combined work to be covered under GPLv3 or other compatible license. The Apache 2.0 license is more appropriate for this project because it is more open with respect to distribution of derivative works, as compared to GPLv3. Therefore, as of v0.12.0, I'm changing the project's license from GPLv3 to the less restrictive Apache 2.0 license.
