### ISSUE TITLE
Multiple Reads

### ISSUE THREAD

**Issue by spstiles** [4-20ma/ModbusMaster#5]
I have a unit where I need to read multiple registers from it.  The registers I need are not next to each other and I need to make multiple read requests from the unit.  If I try to do more than 1 read, when I get the values using the getResponseBuffer() function, the results are wrong.  They seem to be the results from the last read and not the current one.  Any help with this would be appreciated.

**Comment by 4-20ma** [comment]
Has this issue been resolved (using the latest version)? If so, please open a new issue.
