### ISSUE TITLE
Arduino 1.5.5 Beta

### ISSUE THREAD

**Issue by dixitsolanki** [4-20ma/ModbusMaster#6]
Hi,
I have used the library for my Arduino Mega2560 with Arduino IDE 1.0.5 r2.
It is working fine.

Couple of days before, I installed Arduino IDE 1.5.5 Beta. I compiled my project & upload to my Mega2560.
The library is not working. It can not get communicated to slave !! I tried simple serial program & it working fine. But this library is not working.
I was confused.
Then later on I decide to use Arduino IDE 1.0.5 r2. Now the library works fine.

So, I think, the library is not supported in Arduino 1.5.5 Beta.

This is For Your Information Only.
Thanks.
Dixit

**Comment by 4-20ma** [comment]
I believe this issue is resolved by PR #2. Please open another issue if you still encounter a problem.
