### ISSUE TITLE
Serial1,2,3 not working on Arduino Mega

### ISSUE THREAD

**Issue by JBecker32** [4-20ma/ModbusMaster#8]
If I try to use Serial1, Serial2 or Serial3 on an Arduino Mega 2560 for the modbus master interface (e.g with: 

ModbusMaster node(Serial1, 4);

the code does not work. Although 'MBSerial' is correctly set to 'Serial1', no output appears on TX1 and the code hangs on MBSerial.flush().

Changing all occurrences of MBSerial to Serial1 in the library works as a workaround for me.
(tested with Arduino IDE 1.5.5-r2)

**Comment by 4-20ma** [comment]
I just made changes to the way the multiple serial interfaces are assigned and it seems to work on the latest IDE (1.6.4). Please reopen an issue if you still encounter this problem.
