### ISSUE TITLE
Arduino - MODBUS - Lib. problem.

### ISSUE THREAD

**Issue by dvj215** [4-20ma/ModbusMaster#9]
// code below.

  Basic.pde - example using ModbusMaster library
  
  This file is part of ModbusMaster.
  
  ModbusMaster is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  ModbusMaster is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with ModbusMaster.  If not, see <http://www.gnu.org/licenses/>.
  
  Written by Doc Walker (Rx)
  Copyright © 2009-2013 Doc Walker <4-20ma at wvfans dot net>
  
*/

#include <ModbusMaster.h>

// instantiate ModbusMaster object as slave ID 2
// defaults to serial port 0 since no port was specified
ModbusMaster node(2);

void setup()
{
  // initialize Modbus communication baud rate
  node.begin(19200);
}

void loop()
{
  static uint32_t i;
  uint8_t j, result;
  uint16_t data[6];
  
  i++;
  
  // set word 0 of TX buffer to least-significant word of counter (bits 15..0)
  node.setTransmitBuffer(0, lowWord(i));
  
  // set word 1 of TX buffer to most-significant word of counter (bits 31..16)
  node.setTransmitBuffer(1, highWord(i));
  
  // slave: write TX buffer to (2) 16-bit registers starting at register 0
  result = node.writeMultipleRegisters(0, 2);
  
  // slave: read (6) 16-bit registers starting at register 2 to RX buffer
  result = node.readHoldingRegisters(2, 6);
  
  // do something with data if read is successful
  if (result == node.ku8MBSuccess)
  {
    for (j = 0; j < 6; j++)
    {
      data[j] = node.getResponseBuffer(j);
    }
  }
}
// code end.

facing problem, message as under.

Arduino: 1.5.6-r2 (Windows 8), Board: "Arduino Due (Programming Port)"

Basic.pde:25: fatal error: ModbusMaster.h: No such file or directory
compilation terminated.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by 4-20ma** [comment]
Please make sure you have the ModbusMaster library located in your Arduino/libraries directory (refer to your Preferences for the exact location). Alternatively, you can open the sketch folder and place it within the libraries directory and it should find the header file.
